version: '3.8'

services:
  solace:
    image: solace/solace-pubsub-standard:latest
    container_name: solace-test
    ports:
      - "55556:55555"  # SMF
      - "8080:8080"    # SEMP
      - "8008:8008"    # Health check
      - "5672:5672"    # AMQP
      - "1883:1883"    # MQTT
      - "9000:9000"    # REST
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - service_smf_port=55556
      - system_scaling_maxconnectioncount=100
      - system_scaling_maxqueuesize=500
      - service_semp_plaintext_port=8080
      - service_smf_compressed_port=55003
      - service_web_transport_port=8008
      - service_mqtt_tcp_port=1883
      - service_amqp_port=5672
    volumes:
      - solace-test-data:/var/lib/solace
    shm_size: 1g
    mem_limit: 4g
    cpus: 2.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/SEMP/v2/config/about/api || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  solace-test-data: 