spring:
  profiles:
    active: local
  application:
    name: trade-ingestion-service

  datasource:
    url: jdbc:postgresql://localhost:5432/deals
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

solace:
  jms:
    enabled: true
    ssl-enabled: true
    truststore: ${SOLACE_TRUSTSTORE:classpath:truststore.jks}
    truststore-password: ${SOLACE_TRUSTSTORE_PASSWORD:changeit}
    host: ${SOLACE_HOST:localhost}
    username: ${SOLACE_USERNAME:default}
    password: ${SOLACE_PASSWORD:default}
    vpn: ${SOLACE_VPN:default}

deal:
  id:
    service:
      url: ${DEAL_ID_SERVICE_URL:http://localhost:8082/api/deal-ids}
  transformation:
    service:
      url: ${DEAL_TRANSFORMATION_SERVICE_URL:http://localhost:8082/api/transform}

server:
  port: 8080

logging:
  level:
    root: INFO
    com.magiccode.tradeingestion: DEBUG
    org.springframework.cache: TRACE
    io.github.resilience4j: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,circuitbreakers,ratelimiters,retries
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
    retries:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:deals}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
  ratelimiter:
    configs:
      default:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true 