apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-ingestion
  labels:
    app: trade-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-ingestion
  template:
    metadata:
      labels:
        app: trade-ingestion
    spec:
      containers:
      - name: trade-ingestion
        image: trade-ingestion-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: trade-ingestion-config
              key: spring_profile
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: trade-ingestion-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: trade-ingestion-config
              key: db_port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: trade-ingestion-secrets
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: trade-ingestion-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trade-ingestion-secrets
              key: db_password
        - name: SOLACE_HOST
          valueFrom:
            configMapKeyRef:
              name: trade-ingestion-config
              key: solace_host
        - name: SOLACE_PORT
          valueFrom:
            configMapKeyRef:
              name: trade-ingestion-config
              key: solace_port
        - name: SOLACE_VPN
          valueFrom:
            configMapKeyRef:
              name: trade-ingestion-config
              key: solace_vpn
        - name: SOLACE_USERNAME
          valueFrom:
            secretKeyRef:
              name: trade-ingestion-secrets
              key: solace_username
        - name: SOLACE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trade-ingestion-secrets
              key: solace_password
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: trade-ingestion
spec:
  selector:
    app: trade-ingestion
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
