name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn -B test --file pom.xml
    
    - name: Build Docker image
      run: docker build -t deal-ingestion-service .
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Tag and push Docker image
      run: |
        docker tag deal-ingestion-service ghcr.io/${{ github.repository }}/deal-ingestion-service:latest
        docker tag deal-ingestion-service ghcr.io/${{ github.repository }}/deal-ingestion-service:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/deal-ingestion-service:latest
        docker push ghcr.io/${{ github.repository }}/deal-ingestion-service:${{ github.sha }} 